on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  publish:
    name: publish to hex.pm
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10.4-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: publish
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
