# .github/workflows/publish.yml

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23.0.2]
        elixir: [1.10.4]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: actions/cache@v1
        id: plts-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/priv/plts')) }}
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Format checker
        run: mix format --check-formatted
      - name: Test
        run: mix test
      - name: Static analysis
        run: mix dialyzer
      - name: Coverage report
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mix coveralls.github
      - name: Publish
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
